# Generated by Django 6.0 on 2026-01-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorcesterWeather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('time', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('apparent_temperature', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_direction', models.FloatField()),
                ('visibility', models.FloatField()),
                ('precipitation_probability', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='WeatherRecord',
        ),
    ]
